---
controller:
  tag: 2.271
  serviceType: NodePort
  storageClass: jenkins-pv
  installPlugins:
    - configuration-as-code:1.46
    - kubernetes:1.28.4
    - workflow-aggregator:2.6
    - workflow-job:2.40
    - credentials-binding:1.24
    - job-dsl:1.77
    - git:4.5.0

  serviceAccount:
    create: false
    name: jenkins
    annotations: {}

  JCasC:
    enabled: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Configured by Configuration as Code plugin
          clouds:
            - kubernetes:
              name: kubernetes
              serverUrl: https://192.168.99.102:8443
              namespace: jenkins
              jenkinsUrl: http://172.17.0.3:8080
              templates:
                - name: k8s-agent
                  idleMinutes: 30
                  namespace: jenkins
                  nodeUsageMode: NORMAL
                  serviceAccount: jenkins
                  containers:
                    - name: jnlp
                    image: jenkins/inbound-agent:4.3-9-alpine
                    ttyEnabled: true
                  volumes:
                    - persistentVolumeClaim:
                      claimName: jenkins-pv
                      mountPath: /home/jenkins/
                      readOnly: false
        unclassified:
          location:
            adminAddress: "den.karabanov@gmail.com"
