---
controller:
  tag: 2.271
  serviceType: NodePort
  storageClass: jenkins-pv
  installPlugins:
    - configuration-as-code:1.46
    - kubernetes:1.28.4
    - workflow-aggregator:2.6
    - workflow-job:2.40
    - credentials-binding:1.24
    - job-dsl:1.77
    - git:4.5.0

  serviceAccount:
    create: false
    name: jenkins
    annotations: {}

  JCasC:
    enabled: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Configured by Configuration as Code plugin
          clouds:
            - kubernetes:

